<?php
/** op-unit-orm:/testcase/menu.phtml
 *
 * @created   2019-04-19
 * @moved     2020-08-23
 * @version   1.0
 * @package   op-unit-orm
 * @author    Tomoaki Nagahara <tomoaki.nagahara@gmail.com>
 * @copyright Tomoaki Nagahara All right reserved.
 */

/** namespace
 *
 */
namespace OP;

?>
<section>
	|
	<a href="?selftest=1" >Selftest</a> |
	<a href="?" >Create</a> |
	<a href="?form=1" >Form</a> |
</section>
